[build]
  publish = "."
  command = "echo 'No build step required for static site'"

# Basic headers for CSS and JS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"